---
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "30 0 * * *"

jobs:
  test-setup:
    strategy:
      fail-fast: false
      matrix:
        # For info on the OS versions, architecture, etc., see
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout with-extensions branch of janestreet/opam-repository
        uses: actions/checkout@v4
        with:
          repository: janestreet/opam-repository
          ref: with-extensions

      - name: Checkout .github for the test.sh script
        uses: actions/checkout@v4
        with:
          path: scripts
          sparse-checkout: |
            .github/workflows/test.sh
          sparse-checkout-cone-mode: false

      - name: Get latest commit hash
        id: with-extensions-rev
        run: |
          HASH=$(git rev-parse HEAD)
          echo "hash=${HASH}" >> "$GITHUB_OUTPUT"
          ls -lah .
          ls -lah scripts/.github/workflows
