---
on:
  workflow_dispatch:
  push:
    branches:
      - with-extensions
      - gha-* # FIXME: remove after debug
  pull_request:
    branches:
      - with-extensions

jobs:
  test-setup:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run Test OxCaml action
        uses: ./.github/actions/test-oxcaml
        with:
          ocaml-compiler: ocaml-variants.5.2.0+ox
